### ISSUE TITLE
ImportError: cannot import name 'log'

### ISSUE THREAD

**Issue by g4z** [jimgreat/sanic_mysql#6]
Running the example code...

```
from sanic import Sanic
from sanic.response import text
from sanic_mysql import SanicMysql 

app = Sanic(__name__)

app.config.update(dict(MYSQL=dict(host='127.0.0.1', port=3306,
                        user='root', password='pwd',
                        db='mysql')))

SanicMysql(app)

@app.route("/mysql")
async def mysq(request):
    val = await request.app.mysql.query('select 10')
    return text(val)
                        
app.run(host="0.0.0.0", port=8000, debug=True, workers=1)
```

... gives me the following error...

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from sanic_mysql import SanicMysql 
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sanic_mysql/__init__.py", line 2, in <module>
    from .core import SanicMysql
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sanic_mysql/core.py", line 1, in <module>
    from sanic.log import log
ImportError: cannot import name 'log'
```

what did i miss?

**Comment by KaiohFernandes** [comment]
What's up, 

See my fork, https://github.com/KaiohFernandes/sanic_mysql/blob/master/sanic_mysql/core.py
It is working

The sanic.log doesn't work, then you need use Python "import logging"

**Comment by g4z** [comment]
excellent. thanks for the help!

**Comment by Air-Zhuang** [comment]
thanks,but when i use debug mode to start project,it will have two welcome person,haha
